### ISSUE TITLE
insecure_docker_registry_list not being applied

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry-incubator/stager#18]
Hi

We have a private docker registry with a self signed certificate.
We update the property in stager job:
capi.stager.insecure_docker_registry_list: [ "somehostname:443" ]

When we try to stage an image we get this message:
```
Iniciando app testDocker en la organización system / espacio test como admin...
Creating container
Successfully created container
Staging...
Staging process started ...
Failed to talk to docker registry: Get https://somehostname:443/v2/: x509: certificate signed by unknown authority
Staging process failed: Exit trace for group:
builder exited with error: failed to fetch metadata from [test] with tag [latest] and insecure registries [] due to 
....
....
Exit status 2
Staging Failed: STG: Exited with status 2
```
Additionally we added in the manifest instance_groups diego-cell, job garden:
garden.insecure_docker_registry_list: [ "somehostname:443" ]

Do you know what else we have to do?

**Comment by rauizab** [comment]
Hi

we were able to deploy it as an app in cloud foundry. I understand that this is not a feature that is available for the open source cf.

Best regards

**Comment by zrob** [comment]
I'm glad to hear you were able to get this working for you.  This feature should be available to all users of CF, so I'll re-open this and look at resolving the issue.

**Comment by ljfranklin** [comment]
Unfortunately the `stager` component and other "bridge" components have been deprecated for some time and we rarely update them anymore. Fortunately, we just tested insecure docker registries in a post-bridge deployment and it works as expected. You'll need to set BOTH `cc.diego.insecure_docker_registry_list` on the API jobs AND `garden.insecure_docker_registry_list` on the garden jobs. Instructions on removing the bridge components can be found [here](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/V3L5ZYIELIKYT73OFXEJWXUMKRLDL3IS/).
