### ISSUE TITLE
Want to use -insecureDockerRegistry when pulling docker images

### ISSUE THREAD

**Issue by nakaji-s** [cloudfoundry-incubator/stager#5]
Currently `-insecureDockerRegistry` can be used only when `DIEGO_DOCKER_CACHE=true`.
I think this flag should allow to launch a docker image hosted on a private registry.

**Comment by ematpl** [comment]
Hi, @nakaji-s,

Yes, I agree that we'd like to support a whitelist of insecure private registries from which to allow staging and running Docker images on CF. I've added https://www.pivotaltracker.com/story/show/100495522 to the Diego tracker and prioritized it in our Docker-specific track, and I expect we'll get to it soon.

Thanks for the request!

Best,
Eric, CF Runtime Diego PM

**Comment by nakaji-s** [comment]
Thanks for adding a story to the pivotaltracker, @ematpl. 

Cheers!
